# Generated by Django 5.0.1 on 2026-01-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol_previo_admin',
            field=models.CharField(blank=True, choices=[('jugador', 'Jugador'), ('arbitro', 'Árbitro'), ('ambos', 'Jugador y Árbitro'), ('ninguno', 'Sin rol previo')], help_text='Rol que tenía el usuario antes de ser promovido a admin', max_length=20, null=True),
        ),
    ]
