# Generated by Django 5.0.1 on 2025-12-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_cancha_descripcion_cancha_horario_apertura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='TipoCancha',
        ),
    ]
