# Generated by Django 5.0.1 on 2026-01-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_remove_cancha_tipo_delete_tipocancha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancha',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Canchas'},
        ),
        migrations.AddField(
            model_name='cancha',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
