# Generated by Django 5.0.1 on 2026-01-18 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hero",
        ),
    ]
