# Generated by Django 5.0.1 on 2026-01-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen_pos_x',
            field=models.IntegerField(default=50, help_text='Posición X del punto focal (0-100)'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_pos_y',
            field=models.IntegerField(default=50, help_text='Posición Y del punto focal (0-100)'),
        ),
    ]
