# Generated by Django 5.2.7 on 2025-10-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hero_noticia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='partido',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
