# Generated by Django 5.0.1 on 2026-01-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticajugador',
            name='derrotas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
