# Generated by Django 5.0.1 on 2026-01-18 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0005_partido_equipo1_partido_equipo2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partido",
            name="ganador",
        ),
        migrations.RemoveField(
            model_name="partido",
            name="jugadores",
        ),
    ]
