# Generated by Django 5.0.1 on 2026-01-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_remove_partido_ganador_remove_partido_jugadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Torneo Cancelado'),
        ),
    ]
