# Generated by Django 5.0.1 on 2026-01-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_add_cancelado_to_torneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='ediciones_resultado',
            field=models.PositiveSmallIntegerField(default=0, help_text='Número de veces que se ha editado el resultado', verbose_name='Ediciones de Resultado'),
        ),
    ]
